### ISSUE TITLE
Missing Declaration for '@nostr-dev-kit/ndk'

### ISSUE THREAD

**Issue by johna1203** [nostr-dev-kit/ndk#63]
I'm currently facing an issue with the usage of the "@nostr-dev-kit/ndk" package in my TypeScript project. I hope someone can help me resolve this problem.

Here's the relevant part of my package.json:

```
"@nostr-dev-kit/ndk": "^0.8.1",
"typescript": "5.1.6"
```

And here's the TypeScript code where the issue is occurring:

```
import NDK from "@nostr-dev-kit/ndk";
```

The error I'm encountering is:

```
'NDK' is declared but its value is never read.ts(6133)
Could not find a declaration file for module '@nostr-dev-kit/ndk'.
```

I've tried to resolve this issue by installing the corresponding types using the command:

```
yarn add -D @types/@nostr-dev-kit/ndk
```

However, it seems that the problem persists even after installing the types.

Could someone guide me on how to properly address this error? It seems like TypeScript is not recognizing the types even after installing them. Any help or suggestions would be greatly appreciated.

Thank you!

**Comment by erskingardner** [comment]
@johna1203 I just had a look at reproducing this with a brand new super simple TS project but haven't managed to get any errors. Here is what I did: 

1. Created a new folder `testing`
2. I created a single `index.ts` file in that directory.
3. Ran `pnpm init` in the directory to create an empty `package.json` file.
4. Ran `pnpm add @nostr-dev-kit/ndk@latest` to get NDK installed. 
5. Opened `index.ts` and added `import NDK from '@nostr-dev-kid/ndk'` at the top of the file. 
6. Created a new instance of NDK just to see that types worked, and they did. 

If you update to the latest NDK do you still get the issue? If so, please give me a bit more info about your project so I can take a closer look.

**Comment by johna1203** [comment]
@erskingardner Hi,

I'm trying to use @nostr-dev-kit/ndk with Next.js. It might be the reason why it's giving an error.

But I'm using version 0.8.1 now, and I noticed that there have been updates to @nostr-dev-kit/ndk. I will try using the latest version to see if it resolves the issue.

**Comment by johna1203** [comment]
@erskingardner  I tried to create a simple project just like you did, but I'm still getting errors... The only difference is that I'm using `yarn`.
![image](https://github.com/nostr-dev-kit/ndk/assets/2994674/0b84382b-2bc5-4861-86cc-98ccf36073e4)

I also, updated the NDK of the project with Nest.js, but the error persists. 
![image](https://github.com/nostr-dev-kit/ndk/assets/2994674/432d4a74-2235-43ca-b345-2f581274e2fd)


It's strange, could the error be in my environment?

**Comment by erskingardner** [comment]
Does this actually stop NDK from connecting to relays and working? I think it's likely this is just an overactive eslint configuration in your environment. 

You can try to restart the typescript server, which might help. Or restart VS Code. I've seen odd errors like this on types from time to time because of that. 

If it's not stopping NDK from working then it's probably fine to ignore.

**Comment by johna1203** [comment]
The error doesn't prevent access to the relays, the downside is the autocompletion of vscode. :/
But, anyway, I'll keep developing and ignore the error.

Thanks,

**Comment by pablof7z** [comment]
sounds like some cache issue with vscode; I've seen that stuff before -- usually restarting vscode or kicking it for a bit fixes it. Closing for now but feel free to reopen if you're able to reproduce this 😀

**Comment by johna1203** [comment]
Hi @pablof7z 

I tried restarting Visual Studio Code, reinstalling, and clearing the Yarn cache; I tried everything but couldn't solve the issue.

So, I decided to conduct a thorough search and eventually identified the cause of the error.

The error occurs with `typescript v5` when the `moduleResolution` is set to `bundler` in the `tsconfig.json`.

https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler

PS: The 'moduleResolution' configuration in the latest Next.js 'tsconfig.json' is set to 'bundler' when a use the create-next-app to create a new NextJS project.

The solution to resolve the problem involves changing the `package.json` file:

New `package.json`:
```json
    "exports": {
        ".": {
            "types": "./dist/index.d.ts",
            "import": "./dist/index.mjs",
            "require": "./dist/index.js"
        }
    },
```

You need to add `./dist/index.d.ts` to the `exports` to resolve this. (But I haven't tested it on TypeScript v4 yet to see if it works.)


Note:
With this solution, my issue gets resolved, but another error is appearing; I think it might be related to TypeScript v5 itself.

```
- error node_modules/websocket-polyfill/lib/index.js (5:0) @ eval
- error TypeError: Cannot set property 'WebSocket' of #<Object> which has only a getter
    at __webpack_require__ (/Users/xxxx/src/XXXXX/XXXXXXX/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/xxxx/src/XXXXX/XXXXXXX/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/nostr/page.tsx:7:76)
    at (ssr)/./src/app/nostr/page.tsx (/Users/xxxx/src/XXXXXX/XXXXXX/.next/server/app/nostr/page.js:1319:1)
    at __webpack_require__ (/Users/xxxx/src/XXXX/XXXXXX/.next/server/webpack-runtime.js:33:43)
null
```

Would it be a good idea to create a new issue for this task?

**Comment by jamesmagoo** [comment]
Having same issue on a vite+typescript react project. https://github.com/nostr-dev-kit/ndk/issues/75 (Apologies for the duplicate issue guys)
